name: Build mod [Desktop+Android]
on: [push]
permissions:
  contents: write
jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 16    
        cache: 'gradle'
        distribution: adopt
    - name: Build mod jar
      run: ./gradlew --no-daemon deploy
    - name: Upload workflow artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
    - name: Upload release asset
      if: ${{ github.ref_type == 'tag' }}
      uses: vesoft-inc/upload-assets@v1.0.0
      with:
        tag: ${{ github.ref_name }}
        asset-path: build/libs/${{ github.event.repository.name }}.jar
          
