name: Build mod [Desktop+Android]

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 16
        distribution: adopt
    - name: Build mod jar
      run: ./gradlew deploy
    - name: Upload workflow artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
    - name: Upload release asset
      if: ${{ github.ref_type == 'tag' }}
      uses: echapmanFromBunnings/upload-release-assets@1.3
      with:
        releaseTag: ${{ github.ref_name }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        files: build/libs/${{ github.event.repository.name }}.jar
        artefactName: ${{ github.event.repository.name }}
